### ISSUE TITLE
GttributeError: 'MyBartForConditionalGeneration' object has no attribute '_generate_beam_search'

### ISSUE THREAD

**Issue by moh-yani** [thu-coai/JointGT#4]
Dear,

I tried to run file finetune_jointgt_bart.sh with "bash finetune_jointgt_bart.sh" and found an error message such as follows:

Epoch:   5%|█▌                              | 1/20 [10:11<3:13:38, 611.49s/it]Iteration:  49%|█████████████▌              | 196/403 [04:45<05:01,  [388/1644]
Epoch:   5%|█▌                              | 1/20 [14:56<4:43:53, 896.51s/it]
Traceback (most recent call last):
  File "cli_gt.py", line 134, in <module>
    main()
  File "cli_gt.py", line 130, in main
    run(args, logger)
  File "/home/yani/disertasi/JointGT/run_gt.py", line 75, in run
    train(args, logger, model, train_dataloader, dev_dataloader, optimizer, scheduler, tokenizer)
  File "/home/yani/disertasi/JointGT/run_gt.py", line 226, in train
    curr_em = inference(model if args.n_gpu == 1 else model.module, dev_dataloader, tokenizer, args, logger)
  File "/home/yani/disertasi/JointGT/run_gt.py", line 269, in inference
    early_stopping=True,)
  File "/root/anaconda3/envs/jointgt2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yani/disertasi/JointGT/modeling_bart.py", line 1925, in generate
    output = self._generate_beam_search(
  File "/root/anaconda3/envs/jointgt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'MyBartForConditionalGeneration' object has no attribute '_generate_beam_search'

Anyone know what happen it does?

Regards,

Mohammad

**Comment by Tsukiaa** [comment]
can you tell me how to solve this problem?
